name: Sync Cache to Main

on:
  pull_request:
    types:
      - closed   # fires when PR is closed (merged or not)

jobs:
  copy-cache:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        id: cache_test
        with:
          ref: main

      - name: Restore cache from PR branch
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/test"  
          key: test
      
      - name: Save ccache
        uses: actions/cache/save@v4
        id: cache_test
        with:
          path: "${{ github.workspace }}/test"
          key: test

